import { buildCompetitionPlan } from './competition-plan.builder';
import {
  resolveByeProgression,
  resolveGeneratedByes,
} from './bye-progression';

function directPlan(playoffFormat: 'single_elimination' | 'double_elimination') {
  return buildCompetitionPlan({
    crossoverTemplate: [],
    directSeedTeamIds: ['team-1', 'team-2', 'team-3', 'team-4', 'team-5'],
    playoffFormat,
    pools: [],
    qualifiersPerPool: 0,
    qualifyingFormat: 'none',
  });
}

describe('generated bye progression', () => {
  it('advances seeded teams through single-elimination byes', () => {
    const resolved = resolveGeneratedByes(directPlan('single_elimination'));
    const firstRound = resolved.filter((matchup) => matchup.roundNumber === 1);

    expect(firstRound.filter((matchup) => matchup.status === 'final')).toHaveLength(3);
    expect(
      firstRound
        .filter((matchup) => matchup.status === 'final')
        .map((matchup) => matchup.winnerTeamId)
        .sort(),
    ).toEqual(['team-1', 'team-2', 'team-3']);
    expect(
      resolved.find((matchup) => matchup.key === 'SE-R2-M2'),
    ).toEqual(
      expect.objectContaining({
        awayTeamId: 'team-3',
        homeTeamId: 'team-2',
        status: 'ready',
      }),
    );
  });

  it('does not send a nonexistent bye loser into double elimination', () => {
    const resolved = resolveGeneratedByes(directPlan('double_elimination'));
    const byeWinners = resolved.filter(
      (matchup) => matchup.bracketSide === 'winners' && matchup.status === 'final',
    );

    expect(byeWinners).toHaveLength(3);
    expect(byeWinners.every((matchup) => matchup.loserTeamId === null)).toBe(true);
    expect(
      resolved.some(
        (matchup) =>
          matchup.bracketSide === 'losers' &&
          matchup.status === 'void' &&
          matchup.winnerTeamId === null,
      ),
    ).toBe(true);
  });

  it('auto-advances a real loser when the other losers-bracket source was a bye', () => {
    const initiallyResolved = resolveGeneratedByes(
      directPlan('double_elimination'),
    );
    const afterPlayedGame = initiallyResolved.map((matchup) =>
      matchup.key === 'WB-R1-M2'
        ? {
            ...matchup,
            loserTeamId: 'team-5',
            status: 'final' as const,
            winnerTeamId: 'team-4',
          }
        : matchup,
    );

    expect(
      resolveByeProgression(afterPlayedGame).find(
        (matchup) => matchup.key === 'LB-R1-M1',
      ),
    ).toEqual(
      expect.objectContaining({
        status: 'final',
        winnerTeamId: 'team-5',
      }),
    );
  });
});
