/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuthAuthAccounts {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  provider: string;
  provider_account_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface AuthAuthSessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  revoked_at: Timestamp | null;
  session_token_hash: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface AuthPasswordCredentials {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  password_hash: string;
  password_updated_at: Generated<Timestamp>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface AuthRefreshTokens {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  revoked_at: Timestamp | null;
  rotated_from_token_id: string | null;
  session_id: string;
  token_hash: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface AuthUsers {
  created_at: Generated<Timestamp>;
  email: string;
  email_verified: Generated<boolean>;
  id: Generated<string>;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  "auth.auth_accounts": AuthAuthAccounts;
  "auth.auth_sessions": AuthAuthSessions;
  "auth.password_credentials": AuthPasswordCredentials;
  "auth.refresh_tokens": AuthRefreshTokens;
  "auth.users": AuthUsers;
}
