/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AccessAuditEvents {
  action: string;
  actor_member_id: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  metadata: Generated<Json>;
  organization_id: string;
  target_id: string | null;
  target_type: string;
}

export interface AccessGameScorekeeperAssignments {
  created_at: Generated<Timestamp>;
  game_id: string;
  id: Generated<string>;
  organization_member_id: string;
}

export interface AccessOrganizationInvitations {
  accepted_at: Timestamp | null;
  accepted_by_member_id: string | null;
  created_at: Generated<Timestamp>;
  email: string;
  expires_at: Timestamp;
  id: Generated<string>;
  invited_by_member_id: string;
  organization_id: string;
  revoked_at: Timestamp | null;
  role: string;
  status: Generated<string>;
  token_hash: string;
  updated_at: Generated<Timestamp>;
}

export interface AccessTeamManagerAssignments {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  organization_member_id: string;
  team_id: string;
}

export interface AdminDivisions {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  league_season_id: string;
  name: string;
  slug: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface AdminLeagueSeasons {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  organization_id: string;
  public_enabled: Generated<boolean>;
  slug: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface AdminOrganizationMembers {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  organization_id: string;
  role: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface AdminOrganizations {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  slug: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface AdminPlayers {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  jersey_number: string;
  name: string;
  position: Generated<string>;
  status: Generated<string>;
  team_id: string;
  updated_at: Generated<Timestamp>;
}

export interface AdminScheduleGames {
  away_score: number | null;
  away_team_color: string | null;
  away_team_id: string | null;
  away_team_name: string | null;
  away_team_slug: string | null;
  created_at: Timestamp | null;
  division_id: string | null;
  division_name: string | null;
  division_slug: string | null;
  finalized_at: Timestamp | null;
  home_score: number | null;
  home_team_color: string | null;
  home_team_id: string | null;
  home_team_name: string | null;
  home_team_slug: string | null;
  id: string | null;
  league_season_id: string | null;
  league_season_name: string | null;
  league_season_slug: string | null;
  organization_id: string | null;
  published_at: Timestamp | null;
  starts_at: Timestamp | null;
  status: string | null;
  updated_at: Timestamp | null;
  venue_id: string | null;
  venue_name: string | null;
  venue_slug: string | null;
}

export interface AdminTeams {
  color: string | null;
  created_at: Generated<Timestamp>;
  division_id: string;
  id: Generated<string>;
  name: string;
  slug: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface AdminVenues {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  league_season_id: string;
  name: string;
  slug: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface AuthAuthAccounts {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  provider: string;
  provider_account_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface AuthAuthSessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  revoked_at: Timestamp | null;
  session_token_hash: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface AuthPasswordCredentials {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  password_hash: string;
  password_updated_at: Generated<Timestamp>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface AuthRefreshTokens {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  revoked_at: Timestamp | null;
  rotated_from_token_id: string | null;
  session_id: string;
  token_hash: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface AuthUsers {
  created_at: Generated<Timestamp>;
  email: string;
  email_verified: Generated<boolean>;
  id: Generated<string>;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface CompetitionFinalizedGameResults {
  away_score: number | null;
  away_team_id: string | null;
  division_id: string | null;
  finalized_at: Timestamp | null;
  home_score: number | null;
  home_team_id: string | null;
  id: string | null;
  league_season_id: string | null;
  organization_id: string | null;
}

export interface CompetitionGames {
  away_score: number | null;
  away_team_id: string;
  created_at: Generated<Timestamp>;
  division_id: string;
  finalized_at: Timestamp | null;
  home_score: number | null;
  home_team_id: string;
  id: Generated<string>;
  league_season_id: string;
  published_at: Timestamp | null;
  starts_at: Timestamp;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  venue_id: string;
}

export interface PublicPortalLeagueShells {
  division_id: string | null;
  division_name: string | null;
  division_slug: string | null;
  organization_id: string | null;
  organization_name: string | null;
  organization_slug: string | null;
  player_id: string | null;
  player_jersey_number: string | null;
  player_name: string | null;
  season_id: string | null;
  season_name: string | null;
  season_slug: string | null;
  team_color: string | null;
  team_id: string | null;
  team_name: string | null;
  team_slug: string | null;
}

export interface PublicPortalOrganizations {
  organization_id: string | null;
  organization_name: string | null;
  organization_slug: string | null;
  season_id: string | null;
  season_name: string | null;
  season_slug: string | null;
}

export interface DB {
  "access.audit_events": AccessAuditEvents;
  "access.game_scorekeeper_assignments": AccessGameScorekeeperAssignments;
  "access.organization_invitations": AccessOrganizationInvitations;
  "access.team_manager_assignments": AccessTeamManagerAssignments;
  "admin.divisions": AdminDivisions;
  "admin.league_seasons": AdminLeagueSeasons;
  "admin.organization_members": AdminOrganizationMembers;
  "admin.organizations": AdminOrganizations;
  "admin.players": AdminPlayers;
  "admin.schedule_games": AdminScheduleGames;
  "admin.teams": AdminTeams;
  "admin.venues": AdminVenues;
  "auth.auth_accounts": AuthAuthAccounts;
  "auth.auth_sessions": AuthAuthSessions;
  "auth.password_credentials": AuthPasswordCredentials;
  "auth.refresh_tokens": AuthRefreshTokens;
  "auth.users": AuthUsers;
  "competition.finalized_game_results": CompetitionFinalizedGameResults;
  "competition.games": CompetitionGames;
  "public_portal.league_shells": PublicPortalLeagueShells;
  "public_portal.organizations": PublicPortalOrganizations;
}
